# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0679e41a5b5165b68a76ef779e223d67d699612e56d65bb9c539990476792ad7a27bac8e1043822fed550cf3e4db5a3b7d1cd0eb6a2ea7b8883879dc23f9530a

test:
  secret_key_base: 08b75d73ec4f40dfacd3b608b2b173752fa6fce28670adf2c22bd7f389b4e4ede5932ccbe23cfae8b42cfa32eb459b3dc7e9da548af8226306c76cb064e0c43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
